### PR TITLE
Moving the push inside the forEach

### PR DESCRIPTION
**Pull request by webmasterkai**
This might be the problem you are having.

### CODE REVIEW

**Comment by joabakk** [comment]
Not really. I had made this change in my local repo, but all it does is repeat one of the vessels a number of times.

**Comment by joabakk** [comment]
This PR breaks the functionality, so I need to check further. But for now I am happy for the help to get un-stuck

**Comment by webmasterkai** [comment]
I'll take a look a little later and actually test it.

**Comment by joabakk** [comment]
I think this is outdated and will close. Thank you for your help

**Pull request closed without merging**
